default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
      # fast lane - time sensitive jobs only
    - queues: ["latency_10s", "latency_5m"]
      name: fast_<%= Rails.env %>
      threads: 4
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
      # main lane - default jobs and low priority 
    - queues: ["literally_whenever", "free_stickers_sync", "default" ,"*"]
      name: main_<%= Rails.env %>
      threads: 6
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.5

development:
  <<: *default

som_intr_high_seas:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
