# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  15_minutes_hackatime_refresh:
    class: UserHackatimeDataRefreshJob
    command: perform_unique
    queue: default
    schedule: every 15 minutes
    description: "Refresh Hackatime stats for all users with Hackatime enabled"

  # generate_stonk_reports:
  #   class: GenerateStonkReportJob
  #   schedule: every day

  # sync_slack_emotes:
  #   class: SyncSlackEmotesJob
  #   queue: default
  #   schedule: every day
  #   description: "Sync emotes from Slack :yay:"

  update_slack_avatars:
    class: UpdateSlackAvatarJob
    schedule: every 6 hours
    concurrency: 1
    description: "Update all users' Slack avatars from Slack API"

  # cleanup_unattached_storage:
  #   command: "bundle exec rake active_storage:cleanup_unattached[7]"
  #   schedule: every day
  #   description: "Clean up unattached ActiveStorage blobs older than 7 days"

  recalculate_devlog_times:
    class: RecalculateDevlogTimesJob
    command: perform_unique
    schedule: every minute
    concurrency: 1
    description: "Recalculate devlogs' seconds_coded columns"

  sync_user_to_airtable:
    class: SyncUserToAirtableJob
    schedule: every minute
    concurrency: 1
    description: "Sync user data to Airtable every minute with single execution limit"

  sync_email_signup_to_airtable:
    class: SyncEmailSignupToAirtableJob
    schedule: every minute
    concurrency: 1
    description: "Sync email signups to Airtable every minute with single execution limit"

  shop_kick_verification_limbo_orders:
    class: Shop::KickVerificationLimboOrdersJob
    schedule: every 30 minutes
    concurrency: 1
    description: "recheck verf on free stickers orders"

  shop_reap_free_stickers_orders:
    class: Shop::ReapFreeStickersOrdersJob
    schedule: at 1am every day
    concurrency: 1
    description: "fulfill pending free stickers orders into theseus"

  shop_table_sync_free_stickers_orders:
    class: Shop::TableSyncFreeStickersOrdersJob
    schedule: every hour
    concurrency: 1
    description: "CSV-sync free stickers orders into Airtable"

  shop_table_sync_regular_orders:
    class: Shop::TableSyncRegularOrdersJob
    schedule: every 7 minutes
    concurrency: 1
    description: "CSV-sync non-free-stickers orders into Airtable"

  shop_process_letter_mail_orders:
    class: Shop::ProcessLetterMailOrdersJob
    schedule: every 2 days
    concurrency: 1
    description: "Process pending letter mail orders and send to Theseus som-fulfillment queue"

  shop_process_warehouse_orders:
    class: Shop::ProcessWarehouseOrdersJob
    schedule: every 2 days
    concurrency: 1
    description: "Process pending warehouse item orders and create packages for warehouse fulfillment"

  airtable_syncable_update:
    class: AirtableSyncableUpdateJob
    schedule: every 2 minutes
    concurrency: 1
    description: "Sync Airtable records every 2 minutes with single execution limit"

  upload_to_unified_db:
    class: YswsReview::UploadToUnifiedDbJob
    schedule: every 5 minutes
    concurrency: 1
    description: "Upload approved YSWS from the SoM to the Unified db"

  mole_batch_guess_project_categorization:
    class: Mole::BatchGuessProjectCategorizationJob
    schedule: every 12 minutes # 5 times per hour
    concurrency: 1
    description: "Batch guess project categorization using Mole service"