# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  # hourly_hackatime_refresh:
  #   class: HourlyHackatimeRefreshJob
  #   queue: default
  #   schedule: every hour
  #   description: "Refresh Hackatime stats for all users with Hackatime enabled"

  # generate_stonk_reports:
  #   class: GenerateStonkReportJob
  #   schedule: every day

  sync_slack_emotes:
    class: SyncSlackEmotesJob
    queue: default
    schedule: every day
    description: "Sync emotes from Slack :yay:"

  cleanup_unattached_storage:
    command: "bundle exec rake active_storage:cleanup_unattached[7]"
    schedule: every day
    description: "Clean up unattached ActiveStorage blobs older than 7 days"

  recalculate_devlog_times:
    class: RecalculateDevlogTimesJob
    schedule: every minute
    concurrency: 1
    description: "Recalculate devlogs' seconds_coded columns"

  sync_user_to_airtable:
    class: SyncUserToAirtableJob
    schedule: every minute
    concurrency: 1
    description: "Sync user data to Airtable every minute with single execution limit"

  sync_email_signup_to_airtable:
    class: SyncEmailSignupToAirtableJob
    schedule: every minute
    concurrency: 1
    description: "Sync email signups to Airtable every minute with single execution limit"
