# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  hourly_hackatime_refresh:
    class: HourlyHackatimeRefreshJob
    queue: default
    schedule: every hour
    description: "Refresh Hackatime stats for all users with Hackatime enabled"

  generate_stonk_reports:
    class: GenerateStonkReportJob
    schedule: every day

  sync_slack_emotes:
    class: SyncSlackEmotesJob
    queue: default
    schedule: every day
    description: "Sync emotes from Slack :yay:"

  cleanup_unattached_storage:
    command: "bundle exec rake active_storage:cleanup_unattached[7]"
    schedule: every day
    description: "Clean up unattached ActiveStorage blobs older than 7 days"

  pull_airtable_high_seas_book_story_submissions:
    class: PullHighSeasStoriesFromAirtableJob
    queue: default
    schedule: every day
    description: "Pull new High Seas Book story submissions from Airtable"

  recalculate_devlog_times:
    class: RecalculateDevlogTimesJob
    schedule: every hour
    description: "Recalculate all devlogs' seconds_coded columns"

  sync_user_idv_verification_statuses_to_airtable:
    class: SyncUsersIdvVerificationStatusInAirtableJob
    schedule: every hour
    description: "Update all users' verification_status values in the Summer of Making 2025 Airtable `_users` table."
