test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  endpoint: https://<%= Rails.application.credentials.dig(:cloudflare, :account_id) %>.r2.cloudflarestorage.com
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare, :secret_access_key) %>
  region: auto
  bucket: <%= Rails.application.credentials.dig(:cloudflare, :bucket) %>
  # http_open_timeout: 0
  # http_read_timeout: 0
  # retry_limit: 0
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"

# new thingie
cloudflare_new:
  service: S3
  endpoint: https://<%= Rails.application.credentials.dig(:cloudflare_new, :account_id) %>.r2.cloudflarestorage.com
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare_new, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare_new, :secret_access_key) %>
  region: auto
  bucket: <%= Rails.application.credentials.dig(:cloudflare_new, :bucket) %>
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"

# mirror thingie (zero-downtime)
cloudflare_mirror:
  service: Mirror
  primary: cloudflare_new
  mirrors:
    - cloudflare
